controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth
    methods: ['POST']

api_doc:
    path: /api
    controller: api_platform.swagger_ui.action
